export { default as Navbar } from "./Navbar";
export { default as Activites } from "./Activities";
export { default as Home } from "./Home";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as MyRoutines } from "./MyRoutines";
export { default as Routines } from "./Routines";
export { default as CreateRoutine } from "./CreateRoutine";
export { default as CreateActivity} from "./CreateActivities";
export { default as EditRoutine} from "./EditRoutine";
